FROM ruby:2.6.6
ENV RUBYOPT -EUTF-8
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -qq \
    && apt-get install -y nodejs yarn \
    && yarn install --check-files


RUN mkdir /shiori
WORKDIR /shiori
COPY Gemfile /shiori/Gemfile
COPY Gemfile.lock /shiori/Gemfile.lock
COPY . /shiori
RUN mkdir -p tmp/sockets

RUN bundle install
