FROM ruby:2.7.5
ENV RUBYOPT -EUTF-8
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -qq \
    && apt-get install -y nodejs yarn

# add chrome for E2E test
RUN mkdir /downloads
WORKDIR /downloads
ARG CHROME_VERSION="google-chrome-stable"
ARG CHROME_DRIVER_VERSION="latest"
ARG DEBIAN_FRONTEND="noninteractive"
RUN echo "deb http://http.us.debian.org/debian buster main" >> /etc/apt/sources.list \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update -qqy \
    && apt-get -qqy install ${CHROME_VERSION:-google-chrome-stable} \
    && apt-get -qqy install xvfb libxfont2 xorg \
    && rm /etc/apt/sources.list.d/google-chrome.list \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
    && wget https://noto-website-2.storage.googleapis.com/pkgs/Noto-hinted.zip \
    && unzip Noto-hinted.zip \
    && mkdir -p /usr/share/fonts/opentype/noto \
    && cp *otf *ttf /usr/share/fonts/opentype/noto \
    && fc-cache -f -v \
    && CD_VERSION=$(if [ ${CHROME_DRIVER_VERSION:-latest} = "latest" ]; then echo $(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE); else echo $CHROME_DRIVER_VERSION; fi) \
    && echo "Using chromedriver version: "$CD_VERSION \
    && wget --no-verbose -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CD_VERSION/chromedriver_linux64.zip \
    && rm -rf /opt/selenium/chromedriver \
    && unzip /tmp/chromedriver_linux64.zip -d /opt/selenium \
    && rm /tmp/chromedriver_linux64.zip \
    && mv /opt/selenium/chromedriver /opt/selenium/chromedriver-$CD_VERSION \
    && chmod 755 /opt/selenium/chromedriver-$CD_VERSION \
    && ln -fs /opt/selenium/chromedriver-$CD_VERSION /usr/bin/chromedriver

RUN mkdir /shiori
WORKDIR /shiori
COPY Gemfile /shiori/Gemfile
COPY Gemfile.lock /shiori/Gemfile.lock
COPY . /shiori
